# Generated by Django 4.1.3 on 2022-11-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0003_question_alter_choice_question_delete_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
