# Generated by Django 4.1.3 on 2022-11-24 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0004_alter_question_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
    ]
